# Generated by Django 5.2.4 on 2025-09-30 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount paid by this method')),
                ('method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank_transfer'), ('mobile', 'Mobile'), ('points', 'Points')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_status', models.CharField(choices=[('not_settled', 'Not settled'), ('partially_settled', 'Partially Settled'), ('settled', 'Settled')], default='not_settled', max_length=30)),
                ('staff_note', models.TextField(blank=True, max_length=100, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_info', to='payments.payment')),
            ],
        ),
    ]
