# Generated by Django 5.2.4 on 2025-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(help_text='default price in KRW'),
        ),
    ]
