# Generated by Django 5.2.4 on 2025-08-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_packageprice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDailyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField(help_text='daily price in KRW')),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Unavailable')], default='open', help_text='Availability status of the package on a specific date', max_length=15)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Daily Availability',
                'verbose_name_plural': 'Package Daily Availabilities',
                'unique_together': {('package', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='PackagePrice',
        ),
    ]
