# Generated by Django 5.2.4 on 2025-09-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_packagedailyavailability_delete_packageprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.RemoveField(
            model_name='packagedailyavailability',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='base_price',
            field=models.PositiveIntegerField(default=0, help_text='Default base price in KRW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedailyavailability',
            name='cost_price',
            field=models.PositiveIntegerField(default=0, help_text='Override cost price (optional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedailyavailability',
            name='retail_price',
            field=models.PositiveIntegerField(default=0, help_text='Override retail price (optional)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PackageWeekdayBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('retail_price', models.PositiveIntegerField(help_text='Default selling price in KRW')),
                ('cost_price', models.PositiveIntegerField(help_text='Internal coast price in KRW')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_base_prices', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Weekday Base Price',
                'verbose_name_plural': 'Package Weekday Base Prices',
                'unique_together': {('package', 'weekday')},
            },
        ),
    ]
