# Generated by Django 5.2.4 on 2025-07-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('x_coordinate', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('y_coordinate', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('amenities', models.ManyToManyField(related_name='accomodations', to='accommodations.amenity')),
            ],
        ),
    ]
