# Generated by Django 5.2.4 on 2025-07-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='region',
            field=models.CharField(choices=[('seoul', 'Seoul'), ('gyeonggi', 'Gyeonggi'), ('gangwon', 'Gangwon'), ('chungcheong', 'Chungcheong'), ('gyeongsang', 'Gyeongsang'), ('jeolla', 'Jeolla'), ('jeju', 'Jeju')], default='GANGWON', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, related_name='accomodations', to='accommodations.amenity'),
        ),
    ]
