# Generated by Django 5.2.4 on 2025-07-31 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_accommodation_region_alter_accommodation_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort')], default='resort', max_length=10),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations', to='accommodations.city'),
        ),
    ]
