# Generated by Django 5.2.4 on 2025-07-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_city_accommodation_type_accommodation_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
