# Generated by Django 5.2.4 on 2025-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
