# Generated by Django 5.2.4 on 2025-07-30 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0002_accommodation_region_alter_accommodation_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('superSingle', 'SuperSingle'), ('Twin', 'Twin'), ('Queen', 'Queen'), ('king', 'King'), ('SuperKing', 'SuperKing'), ('bunk', 'BUNK'), ('korean', 'Korean Bedding')], max_length=20)),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_occupancy', models.PositiveSmallIntegerField(help_text='기준 인원')),
                ('max_occupancy', models.PositiveSmallIntegerField(help_text='최대 인원')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='객실 면적', max_digits=4, null=True)),
                ('num_living_room', models.PositiveSmallIntegerField(default=1, help_text='거실 수')),
                ('num_bedrooms', models.PositiveSmallIntegerField(default=0, help_text='침실 수')),
                ('num_bathroos', models.PositiveSmallIntegerField(default=0, help_text='화장실 수')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='accommodations.accommodation')),
                ('beds', models.ManyToManyField(blank=True, to='room_types.bedconfiguration')),
            ],
        ),
    ]
