# Generated by Django 5.2.4 on 2025-07-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='num_bathroos',
            new_name='num_bathrooms',
        ),
    ]
