# Generated by Django 5.2.4 on 2025-07-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0002_rename_num_bathroos_roomtype_num_bathrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='beds',
        ),
        migrations.AddField(
            model_name='bedconfiguration',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_config', to='room_types.roomtype'),
        ),
        migrations.AlterUniqueTogether(
            name='bedconfiguration',
            unique_together={('room_type', 'bed_type')},
        ),
    ]
