# Generated by Django 5.2.4 on 2025-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0003_remove_roomtype_beds_bedconfiguration_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedconfiguration',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single'), ('superSingle', 'Super Single'), ('double', 'Double'), ('Queen', 'Queen'), ('king', 'King'), ('superKing', 'Super King'), ('bunk', 'Bunk'), ('korean', 'Korean Bedding')], max_length=20),
        ),
    ]
