# Generated by Django 5.2.4 on 2025-07-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_alter_city_options'),
        ('room_types', '0004_alter_bedconfiguration_bed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='accommodations.accommodation'),
        ),
    ]
