# Generated by Django 5.2.4 on 2025-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0007_alter_roomtype_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='base_occupancy',
            field=models.PositiveSmallIntegerField(default=2, help_text='기준 인원'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.PositiveSmallIntegerField(default=2, help_text='최대 인원'),
        ),
    ]
