# Generated by Django 5.2.4 on 2025-09-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
